#!/bin/bash
#
# clean-ai-attribution-history.sh - Remove AI attribution from commit history
#
# This script uses git filter-repo to surgically remove AI attribution lines
# from all commit messages while preserving human authors and contributions.
#
# WARNING: This rewrites git history. Use with caution.
#
# Policy: AI_ATTRIBUTION_POLICY.md
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}🧹 AI Attribution History Cleanup${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Check if git-filter-repo is installed
if ! command -v git-filter-repo &> /dev/null; then
    echo -e "${RED}❌ Error: git-filter-repo not found${NC}"
    echo ""
    echo "Install git-filter-repo:"
    echo "  brew install git-filter-repo"
    echo "  # or"
    echo "  pip3 install git-filter-repo"
    echo ""
    exit 1
fi

# Safety checks
CURRENT_BRANCH=$(git branch --show-current)

if [ "$CURRENT_BRANCH" != "main" ]; then
    echo -e "${RED}❌ Error: Not on main branch${NC}"
    echo "Current branch: $CURRENT_BRANCH"
    echo ""
    echo "This script must be run from the main branch."
    echo "Switch to main: git checkout main"
    exit 1
fi

if [ -n "$(git status --porcelain)" ]; then
    echo -e "${RED}❌ Error: Working directory not clean${NC}"
    echo ""
    echo "You have uncommitted changes. Please commit or stash them first."
    git status --short
    exit 1
fi

echo -e "${YELLOW}⚠️  WARNING: This will rewrite git history${NC}"
echo ""
echo "This operation will:"
echo "  1. Create a backup branch: backup/pre-attribution-cleanup"
echo "  2. Remove AI attribution from ALL commits"
echo "  3. Preserve all human authors and contributions"
echo "  4. Require force push to update remote"
echo ""
echo "What will be removed:"
echo "  - Similar AI attribution lines"
echo ""
echo "What will be preserved:"
echo "  - All human authors and contributors"
echo "  - All 'Co-Authored-By: [human]' lines"
echo "  - All 'Signed-off-by:' lines"
echo "  - Commit dates, code changes, and everything else"
echo ""

read -p "Continue? (type 'yes' to proceed): " confirmation

if [ "$confirmation" != "yes" ]; then
    echo ""
    echo "Operation cancelled."
    exit 0
fi

echo ""
echo "🔄 Starting cleanup process..."
echo ""

# Create backup branch
BACKUP_BRANCH="backup/pre-attribution-cleanup-$(date +%Y%m%d-%H%M%S)"
git branch "$BACKUP_BRANCH"
echo -e "${GREEN}✅ Created backup branch: $BACKUP_BRANCH${NC}"
echo ""

# Create message filter script
FILTER_SCRIPT=$(mktemp)
cat > "$FILTER_SCRIPT" <<'FILTER_EOF'
#!/usr/bin/env python3
import sys
import re

# Read commit message
message = sys.stdin.read()

# Patterns to remove (AI attribution only, NOT human co-authors)
ai_patterns = [
    r'Co-Authored-By:\s*Claude\s*<[^>]+>\s*\n?',
    r'Co-Authored-By:\s*ChatGPT\s*<[^>]+>\s*\n?',
    r'Co-Authored-By:\s*GitHub Copilot\s*<[^>]+>\s*\n?',
    r'Co-Authored-By:\s*Copilot\s*<[^>]+>\s*\n?',
    r'Co-Authored-By:\s*Cursor\s*<[^>]+>\s*\n?',
    r'Co-Authored-By:\s*Codeium\s*<[^>]+>\s*\n?',
    r'Co-Authored-By:\s*Tabnine\s*<[^>]+>\s*\n?',
    r'Co-Authored-By:\s*Windsurf\s*<[^>]+>\s*\n?',
    r'Co-Authored-By:\s*Amazon Q\s*<[^>]+>\s*\n?',
    r'Co-Authored-By:\s*Anthropic\s*<[^>]+>\s*\n?',
    r'Co-Authored-By:\s*OpenAI\s*<[^>]+>\s*\n?',
    r'Generated by Copilot.*\n?',
    r'🤖\s*Generated with.*\n?',
    r'🤖\s*Created with.*\n?',
    r'🤖\s*Made with.*\n?',
]

# Remove AI attribution patterns
cleaned = message
for pattern in ai_patterns:
    cleaned = re.sub(pattern, '', cleaned, flags=re.IGNORECASE | re.MULTILINE)

# Clean up multiple blank lines
cleaned = re.sub(r'\n\n\n+', '\n\n', cleaned)

# Clean up trailing whitespace
cleaned = cleaned.rstrip() + '\n'

sys.stdout.write(cleaned)
FILTER_EOF

chmod +x "$FILTER_SCRIPT"

echo "🔍 Analyzing repository..."
echo ""

# Run git filter-repo
echo "🔧 Rewriting commit history..."
git filter-repo --force --commit-callback "
import subprocess
commit.message = subprocess.check_output(['$FILTER_SCRIPT'], input=commit.message)
"

echo ""
echo -e "${GREEN}✅ History rewritten successfully${NC}"
echo ""

# Clean up
rm "$FILTER_SCRIPT"

# Show summary
echo "📊 Summary:"
echo ""
echo "  - Backup branch created: $BACKUP_BRANCH"
echo "  - All AI attribution removed from commit messages"
echo "  - Human authors and contributions preserved"
echo ""

# Check if there's a remote
if git remote get-url origin &> /dev/null; then
    REMOTE_URL=$(git remote get-url origin)
    echo -e "${YELLOW}⚠️  Next Steps - Force Push Required${NC}"
    echo ""
    echo "Your local history has been cleaned, but remote still has old commits."
    echo ""
    echo "1. Verify changes:"
    echo "   git log --oneline -20"
    echo "   git log --format='%B' -1  # Check last commit message"
    echo ""
    echo "2. If satisfied, force push to remote:"
    echo "   git push --force-with-lease origin main"
    echo ""
    echo "3. Notify team members to re-clone or rebase their branches"
    echo ""
    echo "4. If something went wrong, restore from backup:"
    echo "   git reset --hard $BACKUP_BRANCH"
    echo ""
    echo "Remote URL: $REMOTE_URL"
else
    echo "✅ No remote configured. History cleaning complete."
fi

echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}🎉 AI Attribution Cleanup Complete!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
